### ISSUE TITLE
Better WhatsApp Share

### ISSUE THREAD

**Issue by arpitnext** [bradvin/social-share-urls#14]
WhatsApp offers advanced sharing features. And, these work for [WhatsApp Web](https://web.whatsapp.com/) as well. 

Source: <https://faq.whatsapp.com/en/android/26000030/?category=5245251>

**Comment by HoldOffHunger** [comment]
Hey, arpitnext,

Good point!  Thanks for the link, I just updated it to reflect that phonenumber is indeed an applicable field for whatsapp, and also added the link, since I'm trying to gather source url's for each of these API's.

Thanks, and let me know if you have any further issues! https://github.com/bradvin/social-share-urls/blob/master/README.md
