### ISSUE TITLE
Signal is missing 

### ISSUE THREAD

**Issue by sarathak** [bradvin/social-share-urls#661]
Can some on can add [signal](https://signal.org/) share button

**Comment by HoldOffHunger** [comment]
Hi, sorry, it doesn't look like this is possible, because Signal has not implemented this.  Please, see the Signal forum discussion on this issue here: https://community.signalusers.org/t/add-custom-url-scheme-signal-or-sgnl-for-share-or-call-buttons-on-websites/2362

>Lets consider having share buttons on websites. A custom url sceme would be a good start to make that possible.

Sorry, not something I can implement for them.  Signal.org will have to implement this in their own code for anyone else to be able to use it.  Good luck.
