### ISSUE TITLE
Add more Social Sharing URLs

### ISSUE THREAD

**Issue by Nirjonadda** [bradvin/social-share-urls#7]
Please add Social Sharing URLs for Surfingbird, WordPress, Flickr, Foursquare, meetup, DeviantArt and BufferApp.

BufferApp:

````
http://bufferapp.com/add?text=[post-title]&url=[post-url]
````

WordPress:

````
http://wordpress.com/press-this.php?u=[post-url]&t=[post-title]&s=[post-desc]&i=[post-img]
````

What for Surfingbird ???

**Comment by sudikrt** [comment]
i cannot post on google plus

**Comment by alexisju** [comment]
Do you have tricks to Mastodon and Diaspora?

**Comment by blausand** [comment]
**[Disclaimer]** Just a few notes on the project, no guarantee for being 100% on topic!  

Interfaces to _commercial bookmark services do harm to the free and open internet_, 
because commercial services do not provide standard protocol APIs to their users' data.  
**Mozillians should patiently educate people to use decentralized alternatives and disencourage usage of those services.**

- Interface to **Diaspora**, **Quitter**, **Wordpress** and **other CMS** makes perfect sense!
- _Mozilla's Sync service_ is self-hostable, but lacks sharing functionality. Perfect integration with Firefox' own bookmark manager (**Library**), for continuously _sharing hives_, would be a lot more desirable.

**On-topic**: These arguments should be communicated as people configurate social sharing URLs

**Comment by HoldOffHunger** [comment]
I like these!  This is the second-to-last issue, and the more interesting of the two outstanding issues, so please, go crazy with listing social media you want this to work for.

Thanks!

**Comment by HoldOffHunger** [comment]
SurfingBird and WordPress added.  More on the way.

**Comment by HoldOffHunger** [comment]
>>"Flickr, Foursquare, meetup, DeviantArt "

Flickr and DeviantArt are sites where the primary submissions are image-files (these are required to make a post).  Foursquare is just a map-sharing service, and meetup is just a meeting service -- there is no API for linking to a particular map location for comments in Foursquare, and there is no API for starting a meeting on meetup from just a link.

So, I don't really think social media applies in these cases.

**Comment by HoldOffHunger** [comment]
@alexisju  !!

You're asking for Mastodon links, when, quite clearly, you have already posted a request to Mastodon.Social, to enable share links. =P  I can't do anything if they won't!

https://github.com/tootsuite/mastodon/issues/1978

Good try, though. =)

And thanks for Diaspora!  Added, tested, and working!

Closing for now. =)
